location          = "westeurope"
sig_name          = "avd_sig"
sig_image_name    = "avd-goldenimage"
sig_image_version = "2025.05.24"
sig_rg_name       = "ramboeck-test-westeurope-rg"
publisher         = "MicrosoftWindowsDesktop"
offer             = "office-365"
